kind: pipeline
type: docker
name: default

environment:
  PMBOT_URL: https://app.pmbot.io
  PMBOT_PROJECT_ID: 5f22f2389e335c4d7f814b33

steps:
  - name: update
    image: pmbot/bot-maven
    environment:
      PMBOT_SSH_PRIVATE_KEY:
        from_secret: PMBOT_SSH_PRIVATE_KEY
      PMBOT_TOKEN:
        from_secret: PMBOT_TOKEN
    commands:
      # skip this job for standard pipelines
      - if [ -z $PMBOT ]; then exit 0; fi
      # make node_modules available to pmbot CLI
      - mvn install
      # run the pmbot CLI
      - pmbot update --disable-host-key-verification

  # your existing build/test jobs
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn install
      - mvn test -B

  # notify pmbot of build status (must be the last step)
  - name: notify
    image: pmbot/bot-maven
    pull: always
    environment:
      PMBOT_TOKEN:
        from_secret: PMBOT_TOKEN
    commands:
      - pmbot notify --debug
