version: "1"
packageManagers:
  - packageManager:
      name: npm
    actions:
      - name: auto-merge
        on:
          - success
          - partial
      #- name: create-issue
       #   on:
        #    - failure
         # config:
          #  token: '${env.MY_TOKEN}'